### ISSUE TITLE
Django 1.8 migrations are broken

### ISSUE THREAD

**Issue by vladlep** [caffeinehit/django-oauth2-provider#124]
Hello,

Django 1.8 migrations are being broken for me. I use django 1.8.4 and  django-oauth2-provider 1.0.1 but i get the error bellow. I overwrote the custom user mode.

I think this issue is related to these:
https://github.com/evonove/django-oauth-toolkit/issues/204
https://code.djangoproject.com/ticket/24524

This project is not maintained anymore but changing now in production would be a lot of work that i am not as happy to do. Did anybody found a solution to this? I found a hack to it by commenting the installed apps, running the migrations and then un-commenting them again:
     # 'provider',
     # 'provider.oauth2',

That is not that nice though and breaks my test running also. 

Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vlad/work/gekkolab/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/vlad/work/gekkolab/ve/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vlad/work/gekkolab/ve/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vlad/work/gekkolab/ve/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/vlad/work/gekkolab/ve/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/home/vlad/work/gekkolab/ve/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 318, in sync_apps
    cursor.execute(statement)
  File "/home/vlad/work/gekkolab/ve/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/vlad/work/gekkolab/ve/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/vlad/work/gekkolab/ve/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/vlad/work/gekkolab/ve/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "accounts_customuser" does not exist

Best,
Vlad

**Comment by blag** [comment]
This project is dead. Please see https://github.com/caffeinehit/django-oauth2-provider/issues/119#issuecomment-76118642 for more information.
