### ISSUE TITLE
not working with django>=1.9

### ISSUE THREAD

**Issue by nazmulhasan85** [caffeinehit/django-oauth2-provider#136]
I am going to upgrade my django project form django=1.8.13 to django=1.10.3 but its failed and showing errors 

`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nazmul/PycharmProjects/django_auth/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/nazmul/PycharmProjects/django_auth/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/home/nazmul/PycharmProjects/django_auth/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nazmul/PycharmProjects/django_auth/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/nazmul/PycharmProjects/django_auth/local/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/nazmul/PycharmProjects/django_auth/local/lib/python2.7/site-packages/provider/oauth2/__init__.py", line 1, in <module>
    import backends
  File "/home/nazmul/PycharmProjects/django_auth/local/lib/python2.7/site-packages/provider/oauth2/backends.py", line 2, in <module>
    from .forms import ClientAuthForm, PublicPasswordGrantForm
  File "/home/nazmul/PycharmProjects/django_auth/local/lib/python2.7/site-packages/provider/oauth2/forms.py", line 10, in <module>
    from .models import Client, Grant, RefreshToken
  File "/home/nazmul/PycharmProjects/django_auth/local/lib/python2.7/site-packages/provider/oauth2/models.py", line 23, in <module>
    class Client(models.Model):
  File "/home/nazmul/PycharmProjects/django_auth/local/lib/python2.7/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/nazmul/PycharmProjects/django_auth/local/lib/python2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/home/nazmul/PycharmProjects/django_auth/local/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
`

**Comment by Dishant15** [comment]
Any updates on this issue? Django 1.10 is out now and generates same error when adding 'provider.oauth2' in installed apps.

**Comment by the-kid89** [comment]
This project has not been updated for 3 years. I don't think its going to happen.

**Comment by nazmulhasan85** [comment]
Yes! I also agree with you @the-kid89 . You can go for an alternative [django-oauth-provider](https://github.com/evonove/django-oauth-toolkit/tree/master/oauth2_provider)
