### ISSUE TITLE
'module' object has no attribute 'oauth2'

### ISSUE THREAD

**Issue by Alisa007** [caffeinehit/django-oauth2-provider#98]
First of all. Thank you! This app would be very helpful if I could manage to make it work.
I try to add OAuth2 authentication scheme to Django rest framework. I'm following the documentation: http://www.django-rest-framework.org/api-guide/authentication It states that 'provider.oauth2' shall be added to INSTALLED_APPS. However, if I do that I keep getting the same error:

Traceback (most recent call last):
  File "/Users/user/s/lib/python3.4/site-packages/django/apps/config.py", line 114, in create
    cls = getattr(mod, cls_name)
AttributeError: 'module' object has no attribute 'oauth2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/PycharmProjects/s/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/user/s/lib/python3.4/site-packages/django/core/management/**init**.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/user/s/lib/python3.4/site-packages/django/core/management/**init**.py", line 354, in execute
    django.setup()
  File "/Users/user/s/lib/python3.4/site-packages/django/**init**.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/user/s/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/user/s/lib/python3.4/site-packages/django/apps/config.py", line 120, in create
    "cannot import name '%s' from '%s'" % (cls_name, mod_path))
ImportError: cannot import name 'oauth2' from 'provider'

Process finished with exit code 1

**Comment by johnlabarge** [comment]
Is there a work around for this?

**Comment by blag** [comment]
CaffeineHit appears to be completely dead, so this repository is no longer being updated.

So no, there is no workaround for this. If you can switch to a different OAuth 2 provider, you can use [Django Oauth Toolkit](https://github.com/evonove/django-oauth-toolkit).

There are forks that are still developed - I suggest either @mapmyfitness's [fork](https://github.com/mapmyfitness/django-oauth2-provider) or @glassresistor's [fork](https://github.com/glassresistor/django-oauth2-provider).

**Comment by dbritos** [comment]
I have the same issue and i not use Django

**Comment by blag** [comment]
@dbritos: If you're sure you're not using Django, you may get that error if you are trying to use the [python-oauth2 library](https://github.com/joestump/python-oauth2) instead, since there is an unfortunate module name collision between that project and this one.
